/**
 * Monthly report → PDF (pdf-lib).
 *
 * Uses pdf-lib's built-in Helvetica fonts, which do not include the rupee
 * glyph, so amounts are written as "Rs. 1,23,456". One A4 page is used;
 * long breakdowns flow onto additional pages automatically.
 */

import { PDFDocument, StandardFonts, rgb, type PDFFont } from 'pdf-lib';

import { listPartyTransactions } from '@/db/party-repo';
import type { MonthReport, Party, PartyBalance, PartyTransaction, PartyType } from '@/types';
import {
  formatDateTime,
  formatINR,
  formatISOToDisplay,
  formatReportRange,
  monthLabel,
} from '@/utils/format';
import { actionForDirection, entryIncreasesBalance, PARTY_ACTIONS } from '@/utils/party';
import {
  computeStatementReport,
  type StatementInclude,
  type StatementReport,
} from '@/utils/statement';

const PAGE_WIDTH = 595.28; // A4 portrait (points)
const PAGE_HEIGHT = 841.89;
const MARGIN = 48;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const GREEN = rgb(0.086, 0.639, 0.29); // ~ #16A34A
const RED = rgb(0.937, 0.267, 0.267); // ~ #EF4444
const DARK = rgb(0.09, 0.09, 0.09);
const GRAY = rgb(0.42, 0.42, 0.42);

/** Indian-grouped amount with an ASCII "Rs." prefix (no ₹ glyph). */
function rupees(amount: number): string {
  const sign = amount < 0 ? '-' : '';
  const grouped = formatINR(Math.abs(amount)).replace('₹', '');
  return `${sign}Rs. ${grouped}`;
}

/**
 * Replaces characters that pdf-lib's built-in WinAnsi fonts cannot encode.
 * Android's `en-IN` locale emits U+202F (narrow no-break space) inside
 * formatted dates, and user-entered text may contain emoji or non-Latin
 * scripts — all of which crash `doc.save()` with "WinAnsi cannot encode …".
 */
function sanitize(text: string): string {
  return text
    .replace(/\u202F/g, ' ') // narrow no-break space (en-IN locale)
    .replace(/\u00A0/g, ' ') // no-break space
    .replace(/₹/g, 'Rs.') // rupee sign (defensive; rupees() already strips it)
    .replace(/[^\x00-\xFF]/g, ''); // drop anything outside WinAnsi/Latin-1
}

interface MonthlyPdfInput {
  /** 0-indexed month. */
  year: number;
  month: number;
  report: MonthReport;
}

export async function buildMonthlyReportPdf({
  year,
  month,
  report,
}: MonthlyPdfInput): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  let page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT - MARGIN;

  /** Draws a line of text, moving to a fresh page when the bottom is near. */
  const line = (text: string, size: number, f: PDFFont, color: ReturnType<typeof rgb>, gap: number) => {
    if (y < MARGIN + 20) {
      page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      y = PAGE_HEIGHT - MARGIN;
    }
    page.drawText(sanitize(text), { x: MARGIN, y, size, font: f, color });
    y -= gap;
  };

  // Header
  line('DailyKhata', 24, bold, DARK, 6);
  line(`Monthly Report - ${monthLabel(year, month)}`, 13, font, GRAY, 18);
  page.drawRectangle({ x: MARGIN, y, width: PAGE_WIDTH - MARGIN * 2, height: 1, color: GRAY });
  y -= 24;

  // Summary
  const { summary } = report;
  const profit = summary.income - summary.expense;
  line('Summary', 16, bold, DARK, 10);
  line(`Income   ${rupees(summary.income)}`, 13, font, GREEN, 22);
  line(`Expense  ${rupees(summary.expense)}`, 13, font, RED, 22);
  line(`Profit   ${rupees(profit)}`, 13, bold, profit >= 0 ? GREEN : RED, 30);

  // Category breakdowns
  const sections: { title: string; items: MonthReport['expenses']; color: ReturnType<typeof rgb> }[] = [
    { title: 'Top Expenses', items: report.expenses, color: RED },
    { title: 'Top Income', items: report.incomes, color: GREEN },
  ];

  for (const section of sections) {
    line(section.title, 16, bold, DARK, 10);
    if (section.items.length === 0) {
      line('Nothing recorded.', 12, font, GRAY, 26);
    } else {
      for (const item of section.items) {
        if (y < MARGIN + 24) {
          page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
          y = PAGE_HEIGHT - MARGIN;
        }
        page.drawText(sanitize(item.name), { x: MARGIN, y, size: 12, font, color: DARK });
        const amount = rupees(item.total);
        const width = font.widthOfTextAtSize(amount, 12);
        page.drawText(sanitize(amount), { x: PAGE_WIDTH - MARGIN - width, y, size: 12, font, color: section.color });
        y -= 20;
      }
    }
    y -= 8;
  }

  // Footer
  line('Generated by DailyKhata - all amounts in rupees.', 10, font, GRAY, 0);

  return doc.save();
}

interface PartyStatementPdfInput {
  name: string;
  phone: string;
  type: PartyType;
  openingBalance: number;
  /** Kept for callers that pass it; the report is rebuilt from `ledger`. */
  balance?: number;
  ledger: PartyTransaction[];
}

/**
 * Convenience wrapper used by the party screen's quick "Share PDF" action.
 * Builds a full statement report from the party's in-memory ledger and renders
 * it with `buildStatementReportPdf` (all-time, all options on).
 */
export async function buildPartyStatementPdf({
  name,
  phone,
  type,
  openingBalance,
  ledger,
}: PartyStatementPdfInput): Promise<Uint8Array> {
  const party: Party = { id: 0, name, phone, type, openingBalance };
  const report = computeStatementReport(party, ledger);
  return buildStatementReportPdf(report, DEFAULT_STATEMENT_INCLUDE);
}

/* ---------------------------------------------------------------------------
 * Statement report PDF (Khatabook-style customer statement)
 * ------------------------------------------------------------------------- */

const BRAND = rgb(0.086, 0.639, 0.29); // ~ #16A34A (app primary green)
const LIGHT = rgb(0.965, 0.973, 0.968); // zebra / panel fill
const BORDER = rgb(0.82, 0.85, 0.84);
const COL_DATE = 62;
const COL_AMOUNT = 80;
const COL_RUNNING = 92;
const CELL_GAP = 8;

const DEFAULT_STATEMENT_INCLUDE: StatementInclude = {
  entryDetails: true,
  notes: true,
  runningBalance: true,
  openingBalance: true,
};

interface ReportColumn {
  key: string;
  label: string;
  x: number;
  width: number;
  align: 'left' | 'right';
}

/** Computes the statement table columns, honoring the include flags. */
function statementColumns(
  include: StatementInclude
): ReportColumn[] {
  const cols: ReportColumn[] = [];
  let x = MARGIN;
  const push = (key: string, label: string, width: number, align: 'left' | 'right' = 'left') => {
    cols.push({ key, label, x, width, align });
    x += width + CELL_GAP;
  };

  push('date', 'Date', COL_DATE);
  if (include.entryDetails) {
    push('desc', 'Description', 0); // width fixed up after the fixed columns
  }
  push('debit', 'Debit (You Gave)', COL_AMOUNT, 'right');
  push('credit', 'Credit (You Got)', COL_AMOUNT, 'right');
  if (include.runningBalance) {
    push('running', 'Running Balance', COL_RUNNING, 'right');
  }

  const desc = cols.find((c) => c.key === 'desc');
  if (desc) {
    const next = cols[cols.indexOf(desc) + 1];
    desc.width = next ? next.x - CELL_GAP - desc.x : PAGE_WIDTH - MARGIN - desc.x;
  }
  return cols;
}

/** Shortens text so it fits a column width (Helvetica has no word wrap). */
function fit(font: PDFFont, text: string, size: number, maxWidth: number): string {
  const safe = sanitize(text);
  if (font.widthOfTextAtSize(safe, size) <= maxWidth) {
    return safe;
  }
  let out = safe;
  while (out.length > 1 && font.widthOfTextAtSize(`${out.slice(0, -1)}…`, size) > maxWidth) {
    out = out.slice(0, -1);
  }
  return `${out.slice(0, -1)}…`;
}

/**
 * A polished, printable A4 party statement, modelled on a Khatabook customer
 * statement and branded for DailyKhata:
 *
 *   logo + business info header  ·  party name & phone  ·  report period &
 *   generated datetime  ·  summary box (opening / debit / credit / net)  ·
 *   statement table grouped by month with monthly + grand totals  ·  page
 *   numbers  ·  all amounts in rupees.
 */
export async function buildStatementReportPdf(
  report: StatementReport,
  include: StatementInclude = DEFAULT_STATEMENT_INCLUDE
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const cols = statementColumns(include);

  let page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT - MARGIN;

  const rightAligned = (text: string, size: number, f: PDFFont, color: ReturnType<typeof rgb>, right: number) => {
    const safe = sanitize(text);
    const width = f.widthOfTextAtSize(safe, size);
    page.drawText(safe, { x: right - width, y, size, font: f, color });
  };
  const cellRight = (col: ReportColumn, text: string, size: number, f: PDFFont, color: ReturnType<typeof rgb>) => {
    const safe = sanitize(text);
    const width = f.widthOfTextAtSize(safe, size);
    page.drawText(safe, { x: col.x + col.width - width, y, size, font: f, color });
  };

  /** Starts a fresh page and redraws the running table headers. */
  const pageBreak = (currentMonthLabel?: string) => {
    page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    y = PAGE_HEIGHT - MARGIN;
    drawTableHeader();
    if (currentMonthLabel) {
      drawMonthHeader(currentMonthLabel);
    }
  };

  const ensureSpace = (needed: number, currentMonthLabel?: string) => {
    if (y - needed < MARGIN + 28) {
      pageBreak(currentMonthLabel);
    }
  };

  const drawTableHeader = () => {
    page.drawRectangle({ x: MARGIN, y: y - 4, width: CONTENT_WIDTH, height: 18, color: LIGHT });
    for (const col of cols) {
      if (col.align === 'right') {
        rightAligned(col.label, 9, bold, DARK, col.x + col.width);
      } else {
        page.drawText(sanitize(col.label), { x: col.x, y, size: 9, font: bold, color: DARK });
      }
    }
    y -= 22;
    page.drawRectangle({ x: MARGIN, y, width: CONTENT_WIDTH, height: 1.2, color: BRAND });
    y -= 10;
  };

  const drawMonthHeader = (label: string) => {
    page.drawRectangle({ x: MARGIN, y: y - 2, width: CONTENT_WIDTH, height: 16, color: LIGHT });
    page.drawText(sanitize(label), { x: MARGIN + 8, y, size: 10.5, font: bold, color: BRAND });
    y -= 20;
  };

  const drawTotalsRow = (label: string, debit: number, credit: number, running?: number) => {
    page.drawText(sanitize(label), { x: MARGIN + 8, y, size: 9.5, font: bold, color: DARK });
    for (const col of cols) {
      if (col.key === 'debit') cellRight(col, rupees(debit), 9.5, bold, DARK);
      if (col.key === 'credit') cellRight(col, rupees(credit), 9.5, bold, DARK);
      if (col.key === 'running' && running !== undefined) cellRight(col, rupees(running), 9.5, bold, DARK);
    }
    y -= 12;
  };

  // ===== Header band: logo + brand + report title =====
  const cx = MARGIN + 14;
  const cy = y - 14;
  page.drawEllipse({ x: cx, y: cy, xScale: 14, yScale: 14, color: BRAND });
  const logoText = 'DK';
  const logoWidth = bold.widthOfTextAtSize(logoText, 12);
  page.drawText(sanitize(logoText), { x: cx - logoWidth / 2, y: cy - 4.5, size: 12, font: bold, color: rgb(1, 1, 1) });

  page.drawText(sanitize('DailyKhata'), { x: MARGIN + 34, y, size: 22, font: bold, color: DARK });
  page.drawText(sanitize('Your khata ledger, made simple'), { x: MARGIN + 34, y: y - 16, size: 9, font, color: GRAY });

  const kind = report.party.type === 'customer' ? 'Customer' : 'Supplier';
  const title = `${kind} Statement`;
  const titleWidth = bold.widthOfTextAtSize(title, 14);
  page.drawText(sanitize(title), { x: PAGE_WIDTH - MARGIN - titleWidth, y: y - 4, size: 14, font: bold, color: BRAND });

  y -= 46;
  page.drawRectangle({ x: MARGIN, y, width: CONTENT_WIDTH, height: 2.5, color: BRAND });
  y -= 18;

  // ===== Party + meta =====
  page.drawText(sanitize(report.party.name), { x: MARGIN, y, size: 16, font: bold, color: DARK });
  y -= 20;
  const partyLine = report.party.phone ? `${kind}  •  ${report.party.phone}` : kind;
  page.drawText(sanitize(partyLine), { x: MARGIN, y, size: 11, font, color: GRAY });
  y -= 18;
  page.drawText(sanitize(`Report period:  ${formatReportRange(report.from, report.to)}`), { x: MARGIN, y, size: 10, font, color: GRAY });
  y -= 14;
  page.drawText(sanitize(`Generated:  ${formatDateTime(report.generatedAt)}`), { x: MARGIN, y, size: 10, font, color: GRAY });
  y -= 20;

  // ===== Summary box =====
  const figures: { label: string; value: string; color?: ReturnType<typeof rgb> }[] = [];
  if (include.openingBalance) {
    figures.push({ label: 'Opening Balance', value: rupees(report.openingBalance) });
  }
  figures.push({ label: 'Total Debit (You Gave)', value: rupees(report.totalDebit) });
  figures.push({ label: 'Total Credit (You Got)', value: rupees(report.totalCredit) });
  figures.push({
    label: 'Net Balance',
    value: rupees(report.netBalance),
    color: report.netBalance >= 0 ? BRAND : RED,
  });

  const figCols = include.openingBalance ? 2 : 3;
  const figRows = Math.ceil(figures.length / figCols);
  const boxPad = 14;
  const boxTitleH = 20;
  const boxRowH = 36;
  const boxHeight = boxPad + boxTitleH + figRows * boxRowH + boxPad;

  page.drawRectangle({ x: MARGIN, y: y - boxHeight, width: CONTENT_WIDTH, height: boxHeight, color: LIGHT });
  page.drawRectangle({ x: MARGIN, y: y - boxHeight, width: CONTENT_WIDTH, height: boxHeight, borderColor: BORDER, borderWidth: 1 });
  page.drawText(sanitize('Summary'), { x: MARGIN + boxPad, y: y - boxPad - 12, size: 12, font: bold, color: DARK });

  const cellW = (CONTENT_WIDTH - boxPad * 2) / figCols;
  figures.forEach((fig, index) => {
    const row = Math.floor(index / figCols);
    const col = index % figCols;
    const fx = MARGIN + boxPad + col * cellW;
    const fy = y - boxPad - boxTitleH - row * boxRowH;
    page.drawText(sanitize(fig.label), { x: fx, y: fy, size: 8.5, font, color: GRAY });
    const safeValue = sanitize(fig.value);
    const valueWidth = bold.widthOfTextAtSize(safeValue, 13);
    page.drawText(safeValue, { x: fx + cellW - valueWidth, y: fy - 16, size: 13, font: bold, color: fig.color ?? DARK });
  });

  y = y - boxHeight - 22;

  // ===== Statement table =====
  drawTableHeader();

  if (include.openingBalance) {
    ensureSpace(18);
    const descCol = cols.find((c) => c.key === 'desc');
    page.drawText(sanitize(formatISOToDisplay(report.from || report.to) || '—'), { x: cols[0].x, y, size: 10, font, color: DARK });
    if (descCol) {
      page.drawText(sanitize('Opening Balance'), { x: descCol.x, y, size: 10, font, color: GRAY });
    }
    const runningCol = cols.find((c) => c.key === 'running');
    if (runningCol) {
      cellRight(runningCol, rupees(report.openingBalance), 10, bold, DARK);
    }
    y -= 16;
  }

  if (report.months.length === 0) {
    page.drawText(sanitize('No entries recorded in this period.'), { x: MARGIN, y: y - 4, size: 11, font, color: GRAY });
  } else {
    for (let m = 0; m < report.months.length; m++) {
      const month = report.months[m];
      ensureSpace(24, month.label);
      drawMonthHeader(month.label);

      for (const entry of month.entries) {
        const rowH = 16 + (include.notes && entry.note ? 12 : 0);
        ensureSpace(rowH + 8, month.label);
        // Zebra stripe for readability.
        if (m % 2 === 0) {
          page.drawRectangle({ x: MARGIN, y: y - 2, width: CONTENT_WIDTH, height: rowH, color: LIGHT });
        }
        for (const col of cols) {
          if (col.key === 'date') {
            page.drawText(sanitize(formatISOToDisplay(entry.date)), { x: col.x, y, size: 10, font, color: DARK });
          } else if (col.key === 'desc') {
            page.drawText(fit(font, entry.description, 10, col.width), { x: col.x, y, size: 10, font, color: DARK });
            if (include.notes && entry.note) {
              page.drawText(fit(font, entry.note, 8.5, col.width), { x: col.x, y: y - 11, size: 8.5, font, color: GRAY });
            }
          } else if (col.key === 'debit' && entry.debit > 0) {
            cellRight(col, rupees(entry.debit), 10, font, DARK);
          } else if (col.key === 'credit' && entry.credit > 0) {
            cellRight(col, rupees(entry.credit), 10, font, DARK);
          } else if (col.key === 'running') {
            cellRight(col, rupees(entry.runningBalance), 10, font, DARK);
          }
        }
        y -= rowH;
      }

      // Month subtotal.
      ensureSpace(20, month.label);
      page.drawRectangle({ x: MARGIN, y: y - 2, width: CONTENT_WIDTH, height: 1, color: BORDER });
      y -= 8;
      const monthEnd = month.entries[month.entries.length - 1].runningBalance;
      drawTotalsRow(`Month Total — ${month.label}`, month.debit, month.credit, include.runningBalance ? monthEnd : undefined);
      y -= 6;
    }
  }

  // ===== Grand total =====
  ensureSpace(30);
  page.drawRectangle({ x: MARGIN, y: y + 6, width: CONTENT_WIDTH, height: 1.6, color: BRAND });
  page.drawRectangle({ x: MARGIN, y: y - 6, width: CONTENT_WIDTH, height: 18, color: LIGHT });
  page.drawText(sanitize('Grand Total'), { x: MARGIN + 8, y, size: 10.5, font: bold, color: DARK });
  for (const col of cols) {
    if (col.key === 'debit') cellRight(col, rupees(report.totalDebit), 10.5, bold, DARK);
    if (col.key === 'credit') cellRight(col, rupees(report.totalCredit), 10.5, bold, DARK);
    if (col.key === 'running') {
      const color = report.netBalance >= 0 ? BRAND : RED;
      cellRight(col, rupees(report.netBalance), 10.5, bold, color);
    }
  }
  y -= 26;

  // ===== Footer page numbers (drawn last, on every page) =====
  const pages = doc.getPages();
  pages.forEach((pageNumber, index) => {
    pageNumber.drawText(sanitize('DailyKhata'), { x: MARGIN, y: 30, size: 9, font, color: GRAY });
    const label = `Page ${index + 1} of ${pages.length}`;
    const width = font.widthOfTextAtSize(label, 9);
    pageNumber.drawText(sanitize(label), { x: (PAGE_WIDTH - width) / 2, y: 30, size: 9, font, color: GRAY });
  });

  return doc.save();
}

interface CombinedPdfInput {
  /** 0-indexed month. */
  year: number;
  month: number;
  /** Monthly report data. */
  report: MonthReport;
  /** All parties with their balances. */
  parties: PartyBalance[];
}

/**
 * A combined PDF with the monthly summary report followed by each party's
 * statement. Useful for sending a single file to an accountant.
 */
export async function buildCombinedPdf({
  year,
  month,
  report,
  parties,
}: CombinedPdfInput): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  let page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT - MARGIN;

  /** Draws a line of text, moving to a fresh page when the bottom is near. */
  const line = (text: string, size: number, f: PDFFont, color: ReturnType<typeof rgb>, gap: number) => {
    if (y < MARGIN + 20) {
      page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      y = PAGE_HEIGHT - MARGIN;
    }
    page.drawText(sanitize(text), { x: MARGIN, y, size, font: f, color });
    y -= gap;
  };

  // ===== MONTHLY REPORT SECTION =====
  line('DailyKhata', 24, bold, DARK, 6);
  line(`Monthly Report - ${monthLabel(year, month)}`, 13, font, GRAY, 18);
  page.drawRectangle({ x: MARGIN, y, width: PAGE_WIDTH - MARGIN * 2, height: 1, color: GRAY });
  y -= 24;

  // Summary
  const { summary } = report;
  const profit = summary.income - summary.expense;
  line('Summary', 16, bold, DARK, 10);
  line(`Income   ${rupees(summary.income)}`, 13, font, GREEN, 22);
  line(`Expense  ${rupees(summary.expense)}`, 13, font, RED, 22);
  line(`Profit   ${rupees(profit)}`, 13, bold, profit >= 0 ? GREEN : RED, 30);

  // Category breakdowns
  const sections: { title: string; items: MonthReport['expenses']; color: ReturnType<typeof rgb> }[] = [
    { title: 'Top Expenses', items: report.expenses, color: RED },
    { title: 'Top Income', items: report.incomes, color: GREEN },
  ];

  for (const section of sections) {
    line(section.title, 16, bold, DARK, 10);
    if (section.items.length === 0) {
      line('Nothing recorded.', 12, font, GRAY, 26);
    } else {
      for (const item of section.items) {
        if (y < MARGIN + 24) {
          page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
          y = PAGE_HEIGHT - MARGIN;
        }
        page.drawText(sanitize(item.name), { x: MARGIN, y, size: 12, font, color: DARK });
        const amount = rupees(item.total);
        const width = font.widthOfTextAtSize(amount, 12);
        page.drawText(sanitize(amount), { x: PAGE_WIDTH - MARGIN - width, y, size: 12, font, color: section.color });
        y -= 20;
      }
    }
    y -= 8;
  }

  // Khata summary
  line('Khata Summary', 16, bold, DARK, 10);
  line(`Money Given   ${rupees(report.party.given)}`, 13, font, RED, 22);
  line(`Money Received ${rupees(report.party.received)}`, 13, font, GREEN, 30);

  // Page break before party statements
  page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  y = PAGE_HEIGHT - MARGIN;

  // ===== PARTY STATEMENTS SECTION =====
  line('DailyKhata', 24, bold, DARK, 6);
  line('Khata Statements (All Parties)', 13, font, GRAY, 18);
  page.drawRectangle({ x: MARGIN, y, width: PAGE_WIDTH - MARGIN * 2, height: 1, color: GRAY });
  y -= 30;

  const customerParties = parties.filter((p) => p.type === 'customer');
  const supplierParties = parties.filter((p) => p.type === 'supplier');

  // Process customers
  if (customerParties.length > 0) {
    line('Customers (They Owe You)', 16, bold, GREEN, 12);
    for (const party of customerParties) {
      y = await drawPartyStatement(doc, page, y, party, font, bold, 'customer');
    }
    y -= 8;
  }

  // Process suppliers
  if (supplierParties.length > 0) {
    line('Suppliers (You Owe Them)', 16, bold, RED, 12);
    for (const party of supplierParties) {
      y = await drawPartyStatement(doc, page, y, party, font, bold, 'supplier');
    }
    y -= 8;
  }

  // Footer
  line('Generated by DailyKhata - all amounts in rupees.', 10, font, GRAY, 0);

  return doc.save();
}

/**
 * Draws a single party statement onto the document.
 * Returns the updated y position.
 */
async function drawPartyStatement(
  doc: PDFDocument,
  page: import('pdf-lib').PDFPage,
  y: number,
  party: PartyBalance,
  font: PDFFont,
  bold: PDFFont,
  type: PartyType
): Promise<number> {
  let currentY = y;

  // Check if we need a new page
  if (currentY < MARGIN + 80) {
    page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    currentY = PAGE_HEIGHT - MARGIN;
  }

  const draw = (text: string, size: number, f: PDFFont, color: ReturnType<typeof rgb>, x = MARGIN) => {
    page.drawText(sanitize(text), { x, y: currentY, size, font: f, color });
    currentY -= size + 2;
  };

  // Party header
  draw(party.name, 14, bold, DARK);
  const kind = type === 'customer' ? 'Customer' : 'Supplier';
  draw(`${kind}${party.phone ? `  •  ${party.phone}` : ''}`, 11, font, GRAY);
  currentY -= 8;

  const isReceivable = party.balance > 0;
  const balanceColor = isReceivable
    ? type === 'customer'
      ? GREEN
      : RED
    : type === 'customer'
    ? RED
    : GREEN;
  draw('Outstanding', 11, bold, balanceColor);
  draw(`${rupees(party.balance)}`, 11, bold, balanceColor, MARGIN + 150);
  currentY -= 12;

  // Load ledger entries for this party
  const ledger = await listPartyTransactions(party.id);

  if (ledger.length === 0) {
    draw('No entries recorded.', 10, font, GRAY);
    currentY -= 10;
    return currentY;
  }

  // Table header
  draw('Date', 10, bold, DARK);
  draw('Entry', 10, bold, DARK, MARGIN + 80);
  draw('Amount', 10, bold, DARK, PAGE_WIDTH - MARGIN - 100);
  currentY -= 12;
  page.drawRectangle({ x: MARGIN, y: currentY, width: PAGE_WIDTH - MARGIN * 2, height: 1, color: GRAY });
  currentY -= 10;

  for (const entry of ledger) {
    if (currentY < MARGIN + 44) {
      page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      currentY = PAGE_HEIGHT - MARGIN;
    }

    const isOpening = entry.kind === 'opening';
    const label = isOpening
      ? 'Opening Balance'
      : PARTY_ACTIONS[actionForDirection(type, entry.direction)].title;
    const amountStr = `${entryIncreasesBalance(type, entry.direction) ? '+' : '-'}${rupees(entry.amount)}`;
    const width = font.widthOfTextAtSize(amountStr, 10);

    page.drawText(sanitize(entry.date), { x: MARGIN, y: currentY, size: 10, font, color: DARK });
    page.drawText(sanitize(label), { x: MARGIN + 80, y: currentY, size: 10, font, color: GRAY });
    page.drawText(sanitize(amountStr), { x: PAGE_WIDTH - MARGIN - width, y: currentY, size: 10, font: bold, color: entryIncreasesBalance(type, entry.direction) ? GREEN : RED });
    currentY -= 14;

    if (entry.note) {
      page.drawText(sanitize(entry.note), { x: MARGIN + 80, y: currentY, size: 9, font, color: GRAY });
      currentY -= 12;
    }
    currentY -= 4;
  }

  currentY -= 6;
  if (currentY > MARGIN) {
    page.drawRectangle({ x: MARGIN, y: currentY, width: PAGE_WIDTH - MARGIN * 2, height: 1, color: GRAY });
    currentY -= 12;
    draw(`Outstanding balance   ${rupees(party.balance)}`, 11, bold, balanceColor);
  }

  return currentY;
}